### ISSUE TITLE
A problem importing module readline

### ISSUE THREAD

**Issue by null12138** [peter-hunt/skyblock#2]
emm
hi bro~
i dont know why i cant using readline
that is warning said
![skyblock](https://user-images.githubusercontent.com/53962221/125218794-3725fa00-e2f6-11eb-9f34-f6ab890f673f.PNG)

**Comment by null12138** [comment]
can  u help me to slove it error?
i am really want to play ur skyblock in cmd

**Comment by null12138** [comment]
btw , i cant install readlne

**Comment by peter-hunt** [comment]
Fixed by replacing the history function with an empty one, in case the module readline cannot be installed or imported. The problem should be fixed so the issue is closed.
