### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by DudeChill** [peter-hunt/skyblock#5]
got this error while trying to install on my main user directory
i cloned the git and then cd skyblock and then ran the command shown here:
```
PS C:\Users\alexg\skyblock> python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-23564.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3312.0_x64__qbz5n2kfra8p0\Lib\site-packages\

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.
```

**Comment by wendellmeset** [comment]
This issue is an easy fix, just go ahead and when you do python setup.py install, make sure your running command prompt as admin, otherwise it has no permission to install!

**Comment by DudeChill** [comment]
> This issue is an easy fix, just go ahead and when you do python setup.py install, make sure your running command prompt as admin, otherwise it has no permission to install!

i will try that out, thanks! i will close this if it works and i just wanted to say i think this project is really cool!

**Comment by DudeChill** [comment]
> This issue is an easy fix, just go ahead and when you do python setup.py install, make sure your running command prompt as admin, otherwise it has no permission to install!

tried that and it didnt fix it :(
