### ISSUE TITLE
Please help, error when running!

### ISSUE THREAD

**Issue by wendellmeset** [peter-hunt/skyblock#6]
This looks great, however I may have a problem. I installed it both via pip, and by building from the repository. However when I use the command "python -m skyblock" it gives me this error:

> Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\Downloads\skyblock-main\skyblock\__main__.py", line 18, in <module>
    skyblock_main()
  File "C:\Users\username\Downloads\skyblock-main\skyblock\__main__.py", line 14, in skyblock_main
    main()
  File "C:\Users\username\Downloads\skyblock-main\skyblock\function\util.py", line 34, in result
    return func(*args, **kwargs)
  File "C:\Users\username\Downloads\skyblock-main\skyblock\menu.py", line 51, in main
    clear()
  File "C:\Users\username\Downloads\skyblock-main\skyblock\function\util.py", line 44, in clear
    call(['clear'])
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by wendellmeset** [comment]
Please help as soon as possible @peter-hunt

**Comment by wendellmeset** [comment]
@peter-hunt I just noticed something, when i install with pip, and run the command "python -m skyblock" it gives me this message: "C:\ProgramData\Anaconda3\python.exe: No module named skyblock.__main__; 'skyblock' is a package and cannot be directly executed" please assist asap!

**Comment by wendellmeset** [comment]
Update on this post, some info and new message: I use Windows 10, on a lenovo computer. To use pip, I use the anaconda command prompt, and I have python 3.8.3!
I updated my pip to the latest version, and now, when using the command "python -m skyblock", i get this message:
"C:\ProgramData\Anaconda3\python.exe: No module named skyblock"

**Comment by DudeChill** [comment]
> Update on this post, some info and new message: I use Windows 10, on a lenovo computer. To use pip, I use the anaconda command prompt, and I have python 3.8.3! I updated my pip to the latest version, and now, when using the command "python -m skyblock", i get this message: "C:\ProgramData\Anaconda3\python.exe: No module named skyblock"

have you tried `cd skyblock` before running the command? im not sure if that fix it but i figure its worth a shot.

**Comment by wendellmeset** [comment]
Hey @DudeChill ! I have already tried cd-ing into skyblock. First it installs the assets successfully, but then it gives me the error message from the original post (the first coomment or the first thing i wrote in this issue, the big error message!)

**Comment by wendellmeset** [comment]
@peter-hunt It has been 9 days, please help me!

**Comment by DudeChill** [comment]
> @peter-hunt It has been 9 days, please help me!

F in the chat for both of us

**Comment by peter-hunt** [comment]
Sorry for the late reply

The game can be executed with `python setup.py install` and `python -m skyblock` (which I did most of the time)

But you can also can `cd` into the project folder, out of the programs folder.
You should see README.md at the same level
Uninstall `skyblock` module with pip first
And then execute `python -m skyblock` to run the folder as a module

I’m not 100% sure this will work tho

**Comment by wendellmeset** [comment]
@peter-hunt sorry for late reply, I had sorta given up. Here is error I get when I do what you say:

> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\username\Downloads\skyblock-main\skyblock-main\skyblock\__main__.py", line 18, in <module>     
>     skyblock_main()
>   File "C:\Users\username\Downloads\skyblock-main\skyblock-main\skyblock\__main__.py", line 14, in skyblock_main
>     main()
>   File "C:\Users\username\Downloads\skyblock-main\skyblock-main\skyblock\function\util.py", line 34, in result  
>     return func(*args, **kwargs)
>   File "C:\Users\username\Downloads\skyblock-main\skyblock-main\skyblock\menu.py", line 51, in main
>     clear()
>   File "C:\Users\username\Downloads\skyblock-main\skyblock-main\skyblock\function\util.py", line 44, in clear   
>     call(['clear'])
>   File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 340, in call
>     with Popen(*popenargs, **kwargs) as p:
>   File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1307, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by BlueSkyNotFound** [comment]
@peter-hunt
for windows use `call(['cls'],shell=True)` instead of `call(['clear'])` in line 44 of [util.py](https://github.com/peter-hunt/skyblock/blob/1135ae69bdb84f36350f4c8c408dab0e6bc24795/skyblock/function/util.py#L44)

**Comment by peter-hunt** [comment]
@BlueSkyNotFound
I added it just now. Thanks for the solution.
